import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/global/header";
import Sidebar from "./components/global/Sidebar";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import {AuthProvider} from './providers/CheckSign.js'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Look Up Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <ClerkProvider>
        <AuthProvider>
      <body className={inter.className}>
        {/* <Header />
        <Sidebar /> */}
        <div className="flex w-full items-center justify-center h-[100vh]">
          {children}

        </div>
       
        </body>
        </AuthProvider>
        </ClerkProvider>
    </html>
    
  );
}
