import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/global/header";
import Sidebar from "./components/global/Sidebar";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
  UserButton
} from '@clerk/nextjs'
import {AuthProvider} from './providers/CheckSign.js'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Look Up Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className={inter.className}>
        <ClerkProvider>
        <AuthProvider>
             {children}      
        </AuthProvider>
        </ClerkProvider>
       
        </body>
       
    </html>
    
  );
}
